---

- name: restart prometheus
  service:
    name: prometheus
    state: restarted

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted

- name: restart grafana
  service:
    name: grafana
    state: restarted
